defaults: &defaults
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: podclik
  password:

development:
  <<: *defaults
  database: podclik_development
  pool: 2

test:
  <<: *defaults
  database: podclik_test

staging:
  <<: *defaults
  database: podclik_staging

production:
  <<: *defaults
  database: podclik_production
  pool: 10
  username: podclik
  password:
